#!/bin/bash

MCU=atmega88p
AVRDUDE="avrdude -p $MCU -c usbasp"

echo "1. Flashing bootloader"
$AVRDUDE -U flash:w:app-simple.hex || exit 1

echo DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE
echo DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE
echo DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE
echo DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE
echo DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE
echo DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE
echo DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE
echo DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE
