#!/bin/bash

MCU=atmega88p
AVRDUDE="avrdude -p $MCU -P /dev/ttyUSB0 -c avr911"

echo "1. Flashing bootloader"
$AVRDUDE -U flash:w:bootloader.hex || exit 1

echo "2. Flashing fuses"
./fuse.sh fuse || exit 1

echo "3. Locking bootloader"
./fuse.sh lock || exit 1

echo DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE
echo DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE
echo DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE
echo DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE
echo DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE
echo DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE
echo DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE
echo DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE DONE
